### PR TITLE
General improvements to the subplugins

### PR DESCRIPTION
**Pull request by naydef**
* Make all abilities work with Boss VS Boss mode
* Make it possible to use one ability in one boss config more than once by adding suffix to the end of the plugin name
* General improvements of the code quality
* Added some new arguments to some abilities
* Discourage the use of FF2_GetBossTeam()

### CODE REVIEW

**Comment by Batfoxkid** [comment]
There is one case where `FF2_GetBossTeam` is used, eg. `FF2_OnAlivePlayersChanged`.

And the KV related stuff is for a clone looking like a different boss.

**Comment by naydef** [comment]
Yea, will eliminate all FF2_GetBossTeam. Now that I checked I don't see FF2_GetBossTeam used in ```FF2_OnAlivePlayersChanged``` or I'm blind

**Comment by Batfoxkid** [comment]
I mean the forward in general needs that native to tell which alive count is in what team.

**Comment by naydef** [comment]
I will leave it like it is for now, because no idea how to deal with this ... mess.

**Pull request merged**
