### PR TITLE
Change hostname to append the boss name

### PR DESCRIPTION
**Pull request by Deathreus**
Just a simple thing I put into the community I work for's fork, their host name is already long, so it cuts off the names, so it's practically useless for them, so I'll put this here

Yes, it's convar controlled.

### CODE REVIEW

**Comment by naydef** [comment]
I think this won't be merged. This will need to be targetted for the experimental branch

**Comment by 50Wliu** [comment]
I'd rather not touch the server's hostname.  This can be implemented in a simple plugin instead.

**Comment by Deathreus** [comment]
I mean, the convar is off by default, they can turn it on if they want to

**Comment by shadow93** [comment]
I should release my hostname boss name plugin, lol.

**Pull request closed without merging**
