### PR TITLE
Added 'FF2_SetClientDamage'

### PR DESCRIPTION
**Pull request by Nopied**
Thanks for reading..

### CODE REVIEW

**Comment by 50Wliu** [comment]
Why?

**Comment by Nopied** [comment]
I think it is useful for subplugins. That's it.

(My English is bad. Sorry D:)

**Comment by shadow93** [comment]
Actually, this is a function i've been needing for a LONG time, Been wanting this for a subplugin so that damage done to a boss's minibosses can be counted

**Comment by 50Wliu** [comment]
Please close this PR and make a new one that targets the `experimental` branch and not stable.  1.10 is receiving maintenance-only patches at this point.

**Comment by Nopied** [comment]
I got it. Thanks :D

**Pull request closed without merging**
