### PR TITLE
Add support for Phil25's RTD (Again)

### PR DESCRIPTION
**Pull request by naydef**
I was thinking to add support for "Be the Robot" plugin with this pull request.

### CODE REVIEW

**Comment by naydef** [comment]
Problem!
```sourcemod FF2_RandomSound >> FF2_FindSound```

**Comment by naydef** [comment]
There is one more subplugin which uses ```FF2_RandomSound```, but the code is commented.

**Comment by 50Wliu** [comment]
Do we still have to `#if defined` and all that?

**Comment by naydef** [comment]
No, but only if you include both RTD includes.

**Pull request merged**
