### PR TITLE
Add support for Phil25's RTD

### PR DESCRIPTION
**Pull request by naydef**
The include file name is different and all natives and forwards have their prefix changed from "RTD_" to "RTD2_". https://forums.alliedmods.net/showthread.php?t=278579&page=3

### CODE REVIEW

**Comment by naydef** [comment]
Someone will see this?

**Comment by 50Wliu** [comment]
I'll comment eventually about my thoughts on this.

**Comment by naydef** [comment]
The other way is if the two files are included at the same time, we will compile the plugin with two files included to make sure rtd will work with the both rtd plugins.

**Comment by 50Wliu** [comment]
I'm still sincerely regretting my initial decision to include Goomba and RTD as optional dependencies inside the main FF2 file.  As such, I want to keep that mistake as minimal as possible, so new plugin dependencies won't be accepted.

Feel free to create a PR to `ff2_external_integration.sp` though!

**Pull request closed without merging**
