### PR TITLE
Boss Pack Change (Without Changing Map Or Restarting)

### PR DESCRIPTION
**Pull request by WakaFloockaFlame**
Hey Guys I Have A Request For FF2 I'm not that good at scripting I  know basics and I mean very basic scripting. If The FF2 team can work together and try to add this function where When the admin changes the boss pack it takes immediate effect without changing map and restarting server not only that for people who don't have the files for the boss pack that you changed 2 it will force that client to rejoin the server therefore being able to download the new files but for people who already have the files it will just take immediate effect I'm just curious if this is even possible. Good Luck If you guys are going to try adding this to FF2

### CODE REVIEW

**Comment by naydef** [comment]
This is is not practical. I think, why there is Boss packs. Different content on different map. Just add all your bosses in one Boss pack, or just add your favorite bosses in one Boss pack. And of course, this is not so easy to add.

**Comment by 50Wliu** [comment]
> 2 it will force that client to rejoin the server therefore being able to download the new files but for people who already have the files it will just take immediate effect I'm just curious if this is even possible.

Not feasible.  Even if it's possible I wouldn't like having to reconnect.  Just change the map, which has the same effect.

Also, you opened this as a pull request, not an issue.

**Comment by WakaFloockaFlame** [comment]
ya i thought so i knew it was 2 hard that would of been so cool though

**Comment by shadow93** [comment]
```sourcepawn
public Action:Command_LoadCharset(client, args)
{
    if(!args)
    {
        CReplyToCommand(client, "{olive}[FF2]{default} Usage: ff2_loadcharset <charset>");
        return Plugin_Handled;
    }
    
    
    new String:charset[32], String:rawText[16][16];
    GetCmdArgString(charset, sizeof(charset));
    new amount=ExplodeString(charset, " ", rawText, 16, 16);
    for(new i; i<amount; i++)
    {
        StripQuotes(rawText[i]);
    }
    ImplodeStrings(rawText, amount, " ", charset, sizeof(charset));

    new String:config[PLATFORM_MAX_PATH];
    BuildPath(Path_SM, config, sizeof(config), "%s/%s", DataPath, CharsetCFG);

    new Handle:Kv=CreateKeyValues("");
    FileToKeyValues(Kv, config);
    for(new i; ; i++)
    {
        KvGetSectionName(Kv, config, sizeof(config));
        if(StrContains(config, charset, false)>=0)
        {
            FF2CharSet=i;
            LoadCharset=true;
            if(CheckRoundState()==FF2RoundState_Setup || CheckRoundState()==FF2RoundState_RoundRunning)
            {
                CReplyToCommand(client, "{olive}[FF2]{default} The current character set is set to be switched to %s!", config);
                return Plugin_Handled;
            }
            
            CReplyToCommand(client, "{olive}[FF2]{default} Character set has been switched to %s", config);
            FindCharacters();
            strcopy(FF2CharSetString, 2, "");
            LoadCharset=false;
            break;
        }

        if(!KvGotoNextKey(Kv))
        {
            CReplyToCommand(client, "{olive}[FF2]{default} Charset not found");
            break;
        }
    }
    CloseHandle(Kv);
    return Plugin_Handled;
}
```

```sourcepawn
public Action:Command_ReloadCharset(client, args)
{
    LoadCharset = true;
    if(CheckRoundState()==FF2RoundState_Setup || CheckRoundState()==FF2RoundState_RoundRunning)
    {
        CReplyToCommand(client, "{olive}[FF2]{default} Current character set is set to reload!");
        return Plugin_Handled;
    }
    CReplyToCommand(client, "{olive}[FF2]{default} Current character set has been reloaded!");
    FindCharacters();
    LoadCharset=false;
    return Plugin_Handled;
}
```

**Comment by WakaFloockaFlame** [comment]
what line number do i add that to? also for people who don't have the files is there gonna be a PrintHintText Saying you need to rejoin the server to install new files or something

**Pull request closed without merging**
